name: kommon
description: kingtous common package collections.
version: 0.1.0-dev.1
homepage: https://kingtous.cn

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.1.0
  photo_view: ^0.13.0
  animations: ^2.0.2
  bruno: ^2.1.0-nullsafety.1
  fl_chart: ^0.45.1
  get: ^4.6.1
  getwidget: ^2.0.5
  pull_to_refresh: ^2.0.0
  jh_debug: ^1.0.1
  fluttertoast: ^8.0.8
  animate_do: ^2.1.0
  shared_preferences: ^2.0.13 # 持久性存储
  flutter_datetime_picker: ^1.5.1
  permission_handler: ^9.2.0 # 权限
  better_player: ^0.0.81
  dio: ^4.0.3
  synchronized: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following video: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
